[theme]
base = "light"
backgroundColor = "#E8E2DB"
secondaryBackgroundColor = "#DDD7D0"
textColor = "#1A1A1A"
primaryColor = "#6B6056"
font = "sans serif"

[server]
headless = true

[client]
toolbarMode = "minimal"
